### ISSUE TITLE
Answers not deleted after forms update

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-ios#43] opened 2018-10-21 11:30 UTC
It seemed to happen on a few phones. Or the app first sent the answers and then got new forms and deleted old answers. Anyhow some answers landed on the server which had newer forms.

Idea: tag answers with a form version and verify in the API

**Comment by CristiHabliuc** [comment] 2019-11-05 18:43
Closing this, as it's a duplicate of #30 (which was never implemented)

**Closed by CristiHabliuc** 2019-11-05 18:43 UTC
Labels: bug, medium-priority
