### ISSUE TITLE
Message Dialog on Push Notification

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ios#178] opened 2019-11-27 13:34 UTC
[Push notifications] Display the received notification in app when the user opens the app by pressing on a received notification.

Current behaviour:
- user has the app closed and receives a push notification that is displayed in the top bar
- the user clicks on the notifications
- the MV app is opened

Expected behaviour:
- user has the app closed and receives a push notification that is displayed in the top bar
- the user clicks on the notifications
- the MV app is opened
- **the notification is displayed in a dialog (same dialog as for the notifications received when the app is opened)**

**Comment by CristiHabliuc** [comment] 2020-02-29 12:52
It seems this is already working as intended. Closing the ticket

**Closed by CristiHabliuc** 2020-02-29 12:52 UTC
Labels: enhancement
